### ISSUE TITLE
Can't build the project

### ISSUE THREAD

**Issue by webmaven** [rodaebel/boboongae#1]
The following steps fail:
1. Create a python 2.5 virtualenv
2. change directory to the virtualenv
3. git clone git://github.com/rodaebel/boboongae.git
4. activate the virtualenv
5. change to the boboongae directory
6. run bootstrap
7. run buildout
8. try to run the app

Basically, I get an AppConfigNotFoundError, apparently because none of the boboongae files were copied or symlinked into parts/boboongae (although various dependency files like bobo are there), so App Engine can't find the app.yaml file. The app works fine if you run it like this: bin/dev_appserver src/boboongae

Suggestions?

**Comment by rodaebel** [comment]
Hi webmaven,

I've updated the buildout configuration and made a couple of quick fixes. It works for me now. Furthermore, I prefer vanilla Python over virtualenv.

Let me know if this works for you too.

Cheers,
Tobias

**Comment by webmaven** [comment]
Tobias, can you explain which changes you made? It seems like a whole bunch of changes were made that might be unrelated to this issue.

In any case, while the application now runs, accessing localhost:8080 produces 'ImportError: No module named cgi'. Are you seeing the same thing?

Thanks, BTW, for an incredibly rapid response!

Michael

**Comment by rodaebel** [comment]
The ImportError you see is very likely caused by virtualenv messing up sys.path. This is due to a flawy Python installation and was discussed in the GAE/Python mailing list a while ago.

I've basically updated bootstrap.py with a newer version and disabled zipimport for the dependencies.

Cheers,
Tobias

**Comment by webmaven** [comment]
Hi Tobias,

Is this the thread you are referencing?: http://groups.google.com/group/google-appengine-python/browse_thread/thread/20f1b4c0b0af5feb

I'm not using OSX, but I suppose the same or similar underlying issue could be affecting Ubuntu. I'll try looking further into it, but I'm a bit out of my depth here.

Using buildout won't prevent all of the accidental namespace pollution that I usually prevent with a virtualenv, so until a fix is found I guess I'll just have to watch out for accidentally importing something that is only installed on the system without being declared as a dependency.

Thanks for the help. I appreciate your looking into an issue that doesn't directly affect you. 

Michael
