### ISSUE TITLE
Transitive dependencies?

### ISSUE THREAD

**Issue by webmaven** [rodaebel/boboongae#3]
Is the rod.recipes.appengine recipe supposed to pull  transitive dependencies into parts? I've noticed that if I pull in a package and it has dependencies, those dependencies get installed in eggs/, but never make it into parts/packagename unless they are individually listed in the buildout.cfg file as well.

Is this the intended behavior? I was under the impression that undeclared dependencies of declared dependencies should Just Work(tm).

**Comment by rodaebel** [comment]
It is intended behavior. Use the 'packages' option http://pypi.python.org/pypi/rod.recipe.appengine to explicitly specify all packages which are required by your GAE app. The recipe automatically installs them in parts/yourapp/packages.zip or parts/yourapp/package.

You might also want to experiment with http://pypi.python.org/pypi/appfy.recipe.gae which is inspired by rod.recipe.appengine but follows a slightly different approach for installing dependencies.

Cheers,
Tobias

**Comment by webmaven** [comment]
Tobias, thanks for the response. The appfy.recipe.gae package looks very interesting. How would you contrast and compare the two?
